---
image:
  name: asia.gcr.io/amartha-dev/amartha/bitbucket-android-flutter-genymotion:1.13
  username: _json_key
  password: "$GCR_DEV_JSON_KEY"

definitions:
  caches:
    flutter-pub-cache: $PUB_CACHE
  steps:
    - step: &analyze-test
        name: Run tests
        script:
          - cd catalog && flutter pub get
          - cd .. && flutter pub get
          - flutter analyze
          - flutter test

    - step: &prepare-build
        name: Prepare build
        caches:
          - flutter-pub-cache
        script:
          - cd catalog
          - flutter pub get

    - step: &build-catalog
        name: Build catalog
        caches:
          - flutter-pub-cache
        script:
          - cd catalog
          - flutter build web --release --web-renderer canvaskitflutter build web --release
        artifacts:
          - catalog/build/web/**


    - step: &build-apk-catalog
        name: Build APK catalog
        caches:
          - flutter-pub-cache
        script:
          - cd catalog
          - flutter build apk --release
        artifacts:
          - catalog/build/app/outputs/flutter-apk/app-release.apk

    - step: &deploy-catalog-main
        name: Deploy catalog main
        script:
          - cd catalog
          - curl -sL https://firebase.tools | bash
          - echo $FIREBASE_SERVICE_ACCOUNT | base64 -d > /tmp/firebase-service-account.json
          - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json
          - firebase deploy --only hosting --non-interactive

    - step: &deploy-catalog-preview
        name: Deploy catalog preview
        script:
          - cd catalog
          - curl -sL https://firebase.tools | bash
          - echo $FIREBASE_SERVICE_ACCOUNT | base64 -d > /tmp/firebase-service-account.json
          - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json
          - ./scripts/deploy_hosting_preview.sh

    - step: &distribute-apk
        name: Distribute apk to firebase
        script:
          - cd catalog/build/app/outputs/flutter-apk/
          - curl -sL https://firebase.tools | bash
          - echo $FIREBASE_SERVICE_ACCOUNT | base64 -d > /tmp/firebase-service-account.json
          - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json
          - firebase appdistribution:distribute app-release.apk --app 1:272130137531:android:5f8cfa98dacbfb63ee389e --groups "flutter-design-system"

clone:
  depth: full

pipelines:
  branches:
    master:
      - step: *analyze-test
      - step: *prepare-build
      - step: *build-catalog
      - step: *deploy-catalog-main
  custom:
    build-dev:
      - step: *prepare-build
      - step: *build-apk-catalog
      - step: *distribute-apk
  pull-requests:
    '{feature/*,bugfix/*}':
      - step: *analyze-test
      - step: *build-catalog
      - step: *deploy-catalog-preview